### ISSUE TITLE
Error handling on line 91 to 101

### ISSUE THREAD

**Issue by bvandervoorn** [Tools4everBV/HelloID-Conn-Prov-Target-ArdaOnline#1]
When you look up a person in arda and the person does not exist the error message returned is: Insufficient permissions to view user

Also ($responseGetUser.data.syncUsers.results.Count -ge 1) is allways true so the elseif ($null -ne $responseGetUser.Errors) will not work. It is best to include this inside of the first statement.

Also $responseGetUser.Error should be $responseGetUser.data.syncUsers.results[0].errors.

So line line 92 to 101 could best be changed to
"    if ($responseGetUser.data.syncUsers.results.Count -ge 1){
        if ($null -ne $responseGetUser.data.syncUsers.results[0].user.externalUserId){
            $action = 'Correlate'
            Write-Verbose -Verbose "About to correlate"
        } elseif (($null -ne $responseGetUser.data.syncUsers.results[0].errors) -and ($responseGetUser.data.syncUsers.results[0].errors[0].message -eq 'User does not exist')){
            $action = 'Create'
            Write-Verbose -Verbose "About to create"
        } elseif ($null -ne $responseGetUser.data.syncUsers.results[0].errors){
            Write-warning "Warning: $($responseGetUser.data.syncUsers.results[0].errors[0].message)"
            $errorMessage = $responseGetUser.data.syncUsers.results[0].errors[0].message
            throw $errorMessage
        }
    }
"

**Comment by JeroenBL** [comment]
solved in V2.
